### ISSUE TITLE
You didn't add a LICENSE file no explained in Readme your permissions over the project 

### ISSUE THREAD

**Issue by goblinrieur** [chochain/eForth1#1]
Hello,

You didn't add a LICENSE file _(GPL/unlicenced/MIT/apache/BSD/....)_ no explained in Readme your permissions over the project 

Get file from choosen license model 

You should create one to avoid any confusion about your code versus our permissions or not :) 

Cause defaut is not "available for all" but "all rights reserved" in fact 

regards.

**Comment by chochain** [comment]
Thank you for noticing. MIT license added.
